Opt("WinWaitDelay",100)
Opt("WinTitleMatchMode",4)
Opt("WinDetectHiddenText",1)
Opt("MouseCoordMode",0)
Run('rtmgr.exe')
WinWait("MiniManager postojów (RadioTaxi Manager 3.1)","")
If Not WinActive("MiniManager postojów (RadioTaxi Manager 3.1)","") Then WinActivate("MiniManager postojów (RadioTaxi Manager 3.1)","")
WinWaitActive("MiniManager postojów (RadioTaxi Manager 3.1)","")
MouseMove(390,30)
MouseDown("left")
MouseUp("left")
WinWait("TaxiManager v3.1","")
If Not WinActive("TaxiManager v3.1","") Then WinActivate("TaxiManager v3.1","")
WinWaitActive("TaxiManager v3.1","")
MouseMove(55,28)
MouseDown("left")
MouseUp("left")
MouseMove(55,43)
MouseDown("left")
MouseUp("left")
MouseMove(55,48)
MouseDown("left")
MouseUp("left")
WinWait("Edytor postojów","")
If Not WinActive("Edytor postojów","") Then WinActivate("Edytor postojów","")
WinWaitActive("Edytor postojów","")
MouseClick("left",52,87,2)
WinWait("Podaj now¹ nazwê postoju","")
If Not WinActive("Podaj now¹ nazwê postoju","") Then WinActivate("Podaj now¹ nazwê postoju","")
WinWaitActive("Podaj now¹ nazwê postoju","")
MouseMove(79,67)
MouseDown("left")
MouseUp("left")
Send("1")
MouseMove(85,95)
MouseDown("left")
MouseUp("left")
WinWait("Edytor postojów","")
If Not WinActive("Edytor postojów","") Then WinActivate("Edytor postojów","")
WinWaitActive("Edytor postojów","")
MouseMove(302,51)
MouseDown("left")
MouseUp("left")
WinWait("TaxiManager v3.1","")
If Not WinActive("TaxiManager v3.1","") Then WinActivate("TaxiManager v3.1","")
WinWaitActive("TaxiManager v3.1","")
MouseMove(55,30)
MouseDown("left")
MouseUp("left")
MouseMove(57,46)
MouseDown("left")
MouseUp("left")
WinWait("Edytor postojów","")
If Not WinActive("Edytor postojów","") Then WinActivate("Edytor postojów","")
WinWaitActive("Edytor postojów","")
MouseClick("left",52,86,2)
WinWait("Podaj now¹ nazwê postoju","")
If Not WinActive("Podaj now¹ nazwê postoju","") Then WinActivate("Podaj now¹ nazwê postoju","")
WinWaitActive("Podaj now¹ nazwê postoju","")
$text = ControlGetText("", "", "TEdit1")
if $text <> "andersa1" then MsgBox(0, "Nieoczekiwana nazwa postoju", $text)
MouseMove(155,105)
MouseDown("left")
MouseUp("left")
WinWait("Edytor postojów","")
If Not WinActive("Edytor postojów","") Then WinActivate("Edytor postojów","")
WinWaitActive("Edytor postojów","")
MouseMove(311,43)
MouseDown("left")
MouseUp("left")
WinWait("TaxiManager v3.1","")
If Not WinActive("TaxiManager v3.1","") Then WinActivate("TaxiManager v3.1","")
WinWaitActive("TaxiManager v3.1","")
MouseMove(65,27)
MouseDown("left")
MouseUp("left")
MouseMove(66,48)
MouseDown("left")
MouseUp("left")
WinWait("Edytor postojów","")
If Not WinActive("Edytor postojów","") Then WinActivate("Edytor postojów","")
WinWaitActive("Edytor postojów","")
MouseClick("left",55,86,2)
WinWait("Podaj now¹ nazwê postoju","")
If Not WinActive("Podaj now¹ nazwê postoju","") Then WinActivate("Podaj now¹ nazwê postoju","")
WinWaitActive("Podaj now¹ nazwê postoju","")
MouseMove(77,65)
MouseDown("left")
MouseUp("left")
Send("{BACKSPACE}")
MouseMove(94,95)
MouseDown("left")
MouseUp("left")
WinWait("Edytor postojów","")
If Not WinActive("Edytor postojów","") Then WinActivate("Edytor postojów","")
WinWaitActive("Edytor postojów","")
MouseMove(298,51)
MouseDown("left")
MouseUp("left")
WinWait("TaxiManager v3.1","")
If Not WinActive("TaxiManager v3.1","") Then WinActivate("TaxiManager v3.1","")
WinWaitActive("TaxiManager v3.1","")
MouseMove(38,31)
MouseDown("left")
MouseUp("left")
MouseMove(62,53)
MouseDown("left")
MouseUp("left")
WinWait("Edytor postojów","")
If Not WinActive("Edytor postojów","") Then WinActivate("Edytor postojów","")
WinWaitActive("Edytor postojów","")
MouseClick("left",67,80,2)
WinWait("Podaj now¹ nazwê postoju","")
If Not WinActive("Podaj now¹ nazwê postoju","") Then WinActivate("Podaj now¹ nazwê postoju","")
WinWaitActive("Podaj now¹ nazwê postoju","")
$text = ControlGetText("", "", "TEdit1")
if $text <> "andersa" then MsgBox(0, "Nieoczekiwana nazwa postoju", $text)
MouseMove(164,95)
MouseDown("left")
MouseUp("left")
WinWait("Edytor postojów","")
If Not WinActive("Edytor postojów","") Then WinActivate("Edytor postojów","")
WinWaitActive("Edytor postojów","")
MouseMove(284,42)
MouseDown("left")
MouseUp("left")
WinWait("TaxiManager v3.1","")
If Not WinActive("TaxiManager v3.1","") Then WinActivate("TaxiManager v3.1","")
WinWaitActive("TaxiManager v3.1","")
MouseMove(639,14)
MouseDown("left")
MouseUp("left")
WinWait("PotwierdŸ","")
If Not WinActive("PotwierdŸ","") Then WinActivate("PotwierdŸ","")
WinWaitActive("PotwierdŸ","")
MouseMove(117,87)
MouseDown("left")
MouseUp("left")
